const fs = require('fs');
const path = require('path');

function text(value) {
  return value && String(value).trim() ? String(value).trim() : '';
}

function lower(value) {
  return String(value || '').toLowerCase();
}

function slugName(value) {
  const s = String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
  return s || 'app';
}

function renderReadme(plan) {
  const steps = Array.isArray(plan.nextSteps) && plan.nextSteps.length ? plan.nextSteps : ['Start building'];
  const lines = [
    '# ' + (text(plan.name) || 'Project'),
    '',
    text(plan.summary) || 'A new project scaffolded by IntelliDev.',
    '',
    '## Stack',
    '',
    '| Layer | Choice |',
    '| --- | --- |',
    '| Frontend | ' + (text(plan.frontend && plan.frontend.stack) || 'None') + ' |',
    '| Backend | ' + (text(plan.backend && plan.backend.stack) || 'None') + ' |',
    '| Database | ' + (text(plan.database && plan.database.name) || 'None') + ' |',
    '| Open with | ' + (text(plan.toolLabel) || text(plan.tool) || '—') + ' |',
    '',
    '## Next steps',
    '',
  ];
  for (const step of steps) lines.push('- [ ] ' + step);
  lines.push('', '> Generated by IntelliDev. See KICKOFF.md for the full build brief.', '');
  return lines.join('\n');
}

function renderKickoff(plan) {
  const steps = Array.isArray(plan.nextSteps) ? plan.nextSteps : [];
  const lines = [
    '# Project Brief: ' + (text(plan.name) || 'Project'),
    '',
    '## Goal',
    text(plan.summary) || 'Build the project described here.',
    '',
    '## UX direction',
    text(plan.ux) || 'Keep it clean and single-purpose.',
    '',
    '## Confirmed stack',
    '- Frontend: ' + (text(plan.frontend && plan.frontend.stack) || 'None'),
    '- Backend: ' + (text(plan.backend && plan.backend.stack) || 'None'),
    '- Database: ' + (text(plan.database && plan.database.name) || 'None'),
    '',
    '## Your task',
    'Scaffold this project from scratch using the stack above. Start with the first steps below, then keep going until you have a minimal, runnable starter.',
  ];
  if (steps.length) {
    lines.push('');
    steps.forEach((step, index) => lines.push(index + 1 + '. ' + step));
  }
  lines.push(
    '',
    '## Constraints',
    '- Keep it minimal and runnable.',
    '- Do not commit or push.',
    '- If .compliance-framework.json is present, respect CSL/DSL/PIPL.',
    '',
  );
  return lines.join('\n');
}

function renderGitignore() {
  return [
    'node_modules/',
    'dist/',
    'build/',
    '.env',
    '.env.*',
    '__pycache__/',
    '*.pyc',
    '.venv/',
    'venv/',
    '.idea/',
    '.vscode/',
    '*.log',
    '.DS_Store',
    '',
  ].join('\n');
}

/* ---------- Template pack ---------- */

function fastapiMain(name) {
  return `from fastapi import FastAPI

app = FastAPI(title="${name}")


@app.get("/")
def root():
    return {"message": "Hello from ${name}"}


@app.get("/health")
def health():
    return {"status": "ok"}
`;
}

function flaskMain(name) {
  return `from flask import Flask, jsonify

app = Flask(__name__)


@app.route("/")
def root():
    return jsonify(message="Hello from ${name}")


@app.route("/health")
def health():
    return jsonify(status="ok")


if __name__ == "__main__":
    app.run(debug=True)
`;
}

function simplePythonMain(name) {
  return `def main():
    print("Hello from ${name}")


if __name__ == "__main__":
    main()
`;
}

function viteIndexHtml(name, mountId, scriptSrc) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${name}</title>
  </head>
  <body>
    <div id="${mountId}"></div>
    <script type="module" src="${scriptSrc}"></script>
  </body>
</html>
`;
}

function reactMainJsx() {
  return `import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
`;
}

function reactAppJsx(name) {
  return `export default function App() {
  return (
    <main style={{ padding: 40, fontFamily: 'system-ui, sans-serif' }}>
      <h1>${name}</h1>
      <p>Edit <code>src/App.jsx</code> and save to reload.</p>
    </main>
  )
}
`;
}

function vueMainJs() {
  return `import { createApp } from 'vue'
import App from './App.vue'

createApp(App).mount('#app')
`;
}

function vueAppSfc(name) {
  return `<template>
  <main>
    <h1>${name}</h1>
    <p>Edit <code>src/App.vue</code> and save to reload.</p>
  </main>
</template>

<style>
main { padding: 40px; font-family: system-ui, sans-serif; }
</style>
`;
}

function expressIndex(name) {
  return `const express = require('express')
const app = express()
const port = process.env.PORT || 3000

app.get('/', (req, res) => res.json({ message: 'Hello from ${name}' }))
app.get('/health', (req, res) => res.json({ status: 'ok' }))

app.listen(port, () => console.log('Listening on :' + port))
`;
}

function reactVitePackage(name) {
  return JSON.stringify(
    {
      name,
      version: '0.1.0',
      private: true,
      type: 'module',
      scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
      dependencies: { react: '^18.3.1', 'react-dom': '^18.3.1' },
      devDependencies: { '@vitejs/plugin-react': '^4.3.4', vite: '^5.4.11' },
    },
    null,
    2,
  ) + '\n';
}

function vueVitePackage(name) {
  return JSON.stringify(
    {
      name,
      version: '0.1.0',
      private: true,
      type: 'module',
      scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
      dependencies: { vue: '^3.5.13' },
      devDependencies: { '@vitejs/plugin-vue': '^5.2.1', vite: '^5.4.11' },
    },
    null,
    2,
  ) + '\n';
}

function nextPackage(name) {
  return JSON.stringify(
    {
      name,
      version: '0.1.0',
      private: true,
      scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
      dependencies: { next: '^14.2.5', react: '^18.3.1', 'react-dom': '^18.3.1' },
    },
    null,
    2,
  ) + '\n';
}

function expressPackage(name) {
  return JSON.stringify(
    {
      name,
      version: '0.1.0',
      private: true,
      scripts: { start: 'node index.js', dev: 'node --watch index.js' },
      dependencies: { express: '^4.21.2' },
    },
    null,
    2,
  ) + '\n';
}

function nodePackage(name) {
  return JSON.stringify(
    { name, version: '0.1.0', private: true, scripts: { start: 'node index.js' } },
    null,
    2,
  ) + '\n';
}

function buildStackFiles(plan) {
  const name = slugName(plan.name);
  const fe = lower(plan.frontend && plan.frontend.stack);
  const be = lower(plan.backend && plan.backend.stack);
  const files = {};

  // Python backend
  if (/fastapi/.test(be)) {
    files['main.py'] = fastapiMain(name);
    files['requirements.txt'] = 'fastapi\nuvicorn[standard]\n';
  } else if (/flask/.test(be)) {
    files['main.py'] = flaskMain(name);
    files['requirements.txt'] = 'flask\n';
  } else if (/django/.test(be)) {
    files['requirements.txt'] = 'django\n';
  } else if (/python/.test(be)) {
    files['main.py'] = simplePythonMain(name);
    files['requirements.txt'] = '';
  }

  // JavaScript frontend / backend
  if (/react/.test(fe)) {
    files['package.json'] = reactVitePackage(name);
    files['index.html'] = viteIndexHtml(name, 'root', '/src/main.jsx');
    files['src/main.jsx'] = reactMainJsx();
    files['src/App.jsx'] = reactAppJsx(name);
  } else if (/vue/.test(fe)) {
    files['package.json'] = vueVitePackage(name);
    files['index.html'] = viteIndexHtml(name, 'app', '/src/main.js');
    files['src/main.js'] = vueMainJs();
    files['src/App.vue'] = vueAppSfc(name);
  } else if (/next/.test(fe)) {
    files['package.json'] = nextPackage(name);
  } else if (/svelte/.test(fe)) {
    files['package.json'] = nodePackage(name);
  } else if (/express/.test(be)) {
    files['package.json'] = expressPackage(name);
    files['index.js'] = expressIndex(name);
  } else if (/node|nest|fastify|koa/.test(be)) {
    files['package.json'] = nodePackage(name);
  }

  return files;
}

function writeScaffold(target, plan) {
  const files = [];
  const write = (name, content) => {
    const filePath = path.join(target, name);
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content, 'utf8');
    files.push(name);
  };

  write('README.md', renderReadme(plan));
  write('.gitignore', renderGitignore());
  write('KICKOFF.md', renderKickoff(plan));
  write('.intellidev.json', JSON.stringify({ ...plan, generatedAt: new Date().toISOString() }, null, 2) + '\n');

  for (const [name, content] of Object.entries(buildStackFiles(plan))) {
    write(name, content);
  }

  return files;
}

module.exports = { writeScaffold };
